### ISSUE TITLE
Github login/authentication fails if no name is specified in github profile

### ISSUE THREAD

**Issue by oscrx** [greenpau/caddy-auth-portal#142]
Github login/authentication fails if no name is specified in Github profile

**Configuration**

```
{
	email xxx
	default_sni domain.nl
	acme_ca https://acme-v02.api.letsencrypt.org/directory
	acme_dns cloudflare {env.CF_API_TOKEN}
	debug
	servers {
		protocol {
			experimental_http3
		}
	}
}

(jwt) {
	jwt {
		primary yes
		set forbidden url https://signin.domain.nl/
		enable js redirect
		set auth url https://signin.domain.nl/auth
		allow roles authp/admin
		crypto key 0001 verify {$JWT_TOKEN}
	}
}

*.domain.nl {
	log {
		output stdout
	}
	@portal {
		host signin.domain.nl
		path /
	}
	route @portal {
		redir auth
	}
	@signin {
		host signin.domain.nl
		path /auth*
	}
	route @signin {
		authp {
			backends {
				github_oauth2_backend {
					method oauth2
					realm github
					provider github
					client_id {$GITHUB_CLIENT}
					client_secret {$GITHUB_SECRET}
					scopes read:org
				}
			}
			transform user {
				exact match sub github.com/throwawayqwerty
				action add role authp/admin
			}
			transform user {
				exact match sub github.com/oscrx
				action add role authp/admin
			}
			cookie domain domain.nl
			cookie lifetime 3600
			crypto default token name access_token
			crypto key 0001 sign-verify {$JWT_TOKEN}
			crypto default token lifetime 3600
			ui {
				links {
					"Portainer" https://portainer.domain.nl
				}
			}
		}
	}
	@portainer host portainer.domain.nl
	route @portainer {
		jwt
		reverse_proxy http://portainer:9000
	}
}

www.domain.nl {
	redir https://domain.nl{uri}
}

```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```bash
ash-4.3# docker exec -it stack_caddy_1 ash
/etc/caddy # caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.3
http.authentication.hashes.scrypt v2.4.3
http.authentication.providers.http_basic v2.4.3
http.handlers.authentication v2.4.3
http.authentication.providers.jwt v1.3.9
http.handlers.authp v1.4.11
```

**Expected behavior**

Decoding OAuth claim does not fail.

**Additional context**

I figured out that the name field in Github cannot be null
Maybe this is the right direction: https://github.com/greenpau/caddy-auth-portal/blob/v1.4.11/pkg/backends/oauth2/user.go#L148
I would try to make a PR myself, but I am really shit at Go 🤷🏻‍♂️

With name:
```
{
  "level": "debug",
  "ts": 1624909243.6488795,
  "logger": "http.handlers.authp",
  "msg": "decoded claims from OAuth 2.0 authorization server access token",
  "request_id": "d991cc8a-bde3-4b1b-934a-22952e9e2f7f",
  "claims": {
    "metadata": {
      "id": 6731096
    },
    "name": "Oscar Wieman",
    "origin": "https://api.github.com/user",
    "picture": "https://avatars.githubusercontent.com/u/6731096?v=4",
    "sub": "github.com/oscrx"
  }
}
```

Without name:
```
{"level":"debug","ts":1624919972.7696624,"logger":"http.stdlib","msg":"http2: panic serving [2001:xxxx:xxxx:xxxx:d945:3eb2:f9c9:b693]:61459: interface conversion: interface {} is nil, not string
goroutine 919 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc00000efa8, 0xc000c15f8e, 0xc00083af00)
net/http/h2_bundle.go:5716 +0x193
panic(0x17a2a60, 0xc0006b1e90)
runtime/panic.go:965 +0x1b9
github.com/greenpau/caddy-auth-portal/pkg/backends/oauth2.(*Backend).fetchClaims(0xc000d8c900, 0xc000d13980, 0x34, 0xc000747900, 0x2)
github.com/greenpau/caddy-auth-portal@v1.4.11/pkg/backends/oauth2/user.go:149 +0x2613
github.com/greenpau/caddy-auth-portal/pkg/backends/oauth2.(*Backend).Authenticate(0xc000d8c900, 0xc000b70000, 0x6, 0xc0002b8001)
github.com/greenpau/caddy-auth-portal@v1.4.11/pkg/backends/oauth2/authenticate.go:116 +0x11e8
github.com/greenpau/caddy-auth-portal/pkg/backends/oauth2.(*Backend).Request(0xc000d8c900, 0x1, 0xc000b70000, 0xc000c67720, 0x7)
github.com/greenpau/caddy-auth-portal@v1.4.11/pkg/backends/oauth2/backend.go:89 +0xef
github.com/greenpau/caddy-auth-portal/pkg/backends.(*Backend).Request(...)
github.com/greenpau/caddy-auth-portal@v1.4.11/pkg/backends/backend.go:101
github.com/greenpau/caddy-auth-portal/pkg/authn.(*Authenticator).handleHTTPExternalLogin(0xc0001eeb40, 0x2431f98, 0xc0004ad800, 0x7f880605cfd8, 0xc000d9f350, 0xc000477b00, 0xc000b70000, 0x1999593, 0x6, 0x0, ...)
github.com/greenpau/caddy-auth-portal@v1.4.11/pkg/authn/handle_external_login.go:60 +0x8f2
github.com/greenpau/caddy-auth-portal/pkg/authn.(*Authenticator).handleHTTP(0xc0001eeb40, 0x2431f98, 0xc0004ad800, 0x7f880605cfd8, 0xc000d9f350, 0xc000477b00, 0xc000b70000, 0xc0004ad800, 0xc000c1e2a0)
github.com/greenpau/caddy-auth-portal@v1.4.11/pkg/authn/respond_http.go:54 +0xe45
github.com/greenpau/caddy-auth-portal/pkg/authn.(*Authenticator).ServeHTTP(0xc0001eeb40, 0x2431f98, 0xc0004ad800, 0x7f880605cfd8, 0xc000d9f350, 0xc000477b00, 0xc000b70000, 0x17d6320, 0x18c1720)
github.com/greenpau/caddy-auth-portal@v1.4.11/pkg/authn/server.go:41 +0x169
github.com/greenpau/caddy-auth-portal.AuthMiddleware.ServeHTTP(0xc0001eeb40, 0x7f880605cfd8, 0xc000d9f350, 0xc000477b00, 0x24129c0, 0xc00036afe0, 0xcf35200, 0x7f880605cfd8)
github.com/greenpau/caddy-auth-portal@v1.4.11/plugin.go:60 +0xbb
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc001087a60, 0x7f880605cfd8, 0xc000d9f170, 0xc000477b00, 0x24129c0, 0xc00036afe0, 0x0, 0x0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/metrics.go:133 +0x548
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x7f880605cfd8, 0xc000d9f170, 0xc000477b00, 0xc00036b0c0, 0xc001087a60)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/routes.go:263 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00036b0c0, 0x7f880605cfd8, 0xc000d9f170, 0xc000477b00, 0x1, 0x0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x7f880605cfd8, 0xc000d9f170, 0xc000477b00, 0x1, 0x1)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/routes.go:235 +0x19f
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00036b0a0, 0x7f880605cfd8, 0xc000d9f170, 0xc000477b00, 0xc00036afe0, 0x24129c0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc000c673c0, 0x7f880605cfd8, 0xc000d9f170, 0xc000477b00, 0x24129c0, 0xc00036afe0, 0xc00036ac60, 0xc00037cb88)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/subroute.go:74 +0x8a
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc001087a80, 0x7f880605cfd8, 0xc000d9e090, 0xc000477b00, 0x24129c0, 0xc00036afe0, 0x0, 0x0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/metrics.go:133 +0x548
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x7f880605cfd8, 0xc000d9e090, 0xc000477b00, 0xc00036b080, 0xc001087a80)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/routes.go:263 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00036b080, 0x7f880605cfd8, 0xc000d9e090, 0xc000477b00, 0x1, 0x0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x7f880605cfd8, 0xc000d9e090, 0xc000477b00, 0x1, 0x1)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/routes.go:235 +0x19f
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00036b060, 0x7f880605cfd8, 0xc000d9e090, 0xc000477b00, 0xc00036afe0, 0x24129c0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc000c67240, 0x7f880605cfd8, 0xc000d9e090, 0xc000477b00, 0x24129c0, 0xc00036afe0, 0xc00036ac60, 0xc00037ce20)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/subroute.go:74 +0x8a
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc001087aa0, 0x7f880605cfd8, 0xc0004adbc0, 0xc000477b00, 0x24129c0, 0xc00036afe0, 0x0, 0x0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/metrics.go:133 +0x548
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x7f880605cfd8, 0xc0004adbc0, 0xc000477b00, 0xc00036b040, 0xc001087aa0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/routes.go:263 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00036b040, 0x7f880605cfd8, 0xc0004adbc0, 0xc000477b00, 0x1, 0x0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x7f880605cfd8, 0xc0004adbc0, 0xc000477b00, 0x1, 0x1)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/routes.go:235 +0x19f
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00036b000, 0x7f880605cfd8, 0xc0004adbc0, 0xc000477b00, 0x21e9208, 0x24129c0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc000c66a40, 0x7f880605cfd8, 0xc0004adbc0, 0xc000477b00, 0x24129c0, 0x21e9208, 0x0, 0x0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/subroute.go:74 +0x8a
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc000e98340, 0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0x24129c0, 0x21e9208, 0x0, 0x0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/metrics.go:133 +0x548
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0xc00036ae00, 0xc000e98340)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/routes.go:263 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00036ae00, 0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0x0, 0xffb200)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0x0, 0xc00104e960)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/routes.go:235 +0x19f
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000e98360, 0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0xc00037d200, 0xffb268)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0x0, 0xc00104e8e8)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/routes.go:203 +0x395
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000e98380, 0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0xc00037d300, 0xffb268)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0x0, 0xc00104e828)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/routes.go:203 +0x395
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000e983a0, 0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0xc00037d300, 0xffb268)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0x0, 0xc00104e7b0)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/routes.go:203 +0x395
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000e983c0, 0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0x0, 0x2)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0x8, 0x18)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/routes.go:203 +0x395
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000e983e0, 0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0xc00037d540, 0x40b739)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0xc0006a1320, 0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0x24129c0, 0xc000e983e0, 0x19b8d5ef3dc95, 0xcf25bcc)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/server.go:295 +0x9d
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1(0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0xc00cf25bcc, 0x19b8d5ef3dc95)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/server.go:271 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000e98400, 0x7f880605cfd8, 0xc0004ad920, 0xc000477b00, 0xc000d19f00, 0xc000477b00)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/caddyhttp.go:57 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc0006a1320, 0x7f880605cfd8, 0xc0004ad920, 0xc000477b00)
github.com/caddyserver/caddy/v2@v2.4.3/modules/caddyhttp/server.go:207 +0x586
net/http.serverHandler.ServeHTTP(0xc000e66ee0, 0x242c3a0, 0xc00000efa8, 0xc000c41e00)
net/http/server.go:2887 +0xa3
net/http.initALPNRequest.ServeHTTP(0x2431f98, 0xc00085e8d0, 0xc0000ae700, 0xc000e66ee0, 0x242c3a0, 0xc00000efa8, 0xc000c41e00)
net/http/server.go:3459 +0x8d
net/http.(*http2serverConn).runHandler(0xc00083af00, 0xc00000efa8, 0xc000c41e00, 0xc000b63080)
net/http/h2_bundle.go:5723 +0x8b
created by net/http.(*http2serverConn).processHeaders
net/http/h2_bundle.go:5453 +0x505"}
```

**Comment by greenpau** [comment]
@oscrx , please upgrade to `v1.4.11` and see if the problem still exists.

Additionally, the following line should be changed:

```
set auth url https://signin.domain.nl/auth/oauth2/github/
```

To:

```
set auth url https://signin.domain.nl/auth
```

The https://github.com/greenpau/caddy-auth-jwt/releases/tag/v1.3.9 automatically recognizes the token was issued by `portal` and redirects to the original issuer, i.e. `https://signin.domain.nl/auth/oauth2/github/`.

Let's see the upgrade to latest works.

**Comment by greenpau** [comment]
The following:

```
  "claims": {
    "metadata": {
      "id": 6731096
    },
    "name": "Oscar Wieman",
    "origin": "https://api.github.com/user",
    "picture": "https://avatars.githubusercontent.com/u/6731096?v=4",
    "sub": "github.com/oscrx"
  }
```

gets created by:

https://github.com/greenpau/caddy-auth-portal/blob/a784a123ccfca3c6608f5a9da0dcf8b89aaa46e1/pkg/backends/oauth2/user.go#L144-L158

**Comment by oscrx** [comment]
Thanks for the quick response, I didn't check if i were on the latest versions. I run Caddy in a custom docker container and the Github actions build I run for it seems to experience some cache issues. Clean build fixed it for me.

Nice feature also, changed my config!

Unfortunately the bug still seems to be there on the latest versions.

Let me know if I can do something else.

**Comment by greenpau** [comment]
@oscrx , please update your original post with the latest outputs, including the error (therexare references to line numbers there)

**Comment by greenpau** [comment]
@oscrx , I got the issue now. Will fix and release a new version.

```
		if v, exists := data["name"]; exists {
			m["name"] = v.(string)
		}
		metadata := make(map[string]interface{})
		if v, exists := data["id"]; exists {
			metadata["id"] = v
		}
		m["metadata"] = metadata
```

The logic needs to account for nil value.

**Comment by greenpau** [comment]
@oscrx , you should be good to go now!

**Comment by oscrx** [comment]
@greenpau Thanks! It works great 👍

**Comment by greenpau** [comment]
@oscrx , please mention caddy and auth portal on the social media platforms! Like, share, praise ;-)
