### ISSUE TITLE
panic on empty config

### ISSUE THREAD

**Issue by porjo** [greenpau/caddy-auth-portal#195]
Using the following Caddfile:
```
{
	http_port 8080
	https_port 4443
	debug
}

localhost {
	log

	tls internal

	root * /home/ian/caddy
	file_server

	route / {
		authorize
	}
}
```
Then attempt to connect to https://localhost:4443, I see this in the log:

```
2021/11/11 04:33:44.029	INFO	http.log.access	handled request	{"request": {"remote_addr": "127.0.0.1:55386", "proto": "HTTP/2.0", "method": "GET", "host": "localhost:4443", "uri": "/", "headers": {"User-Agent": ["curl/7.79.1"], "Accept": ["*/*"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "proto_mutual": true, "server_name": "localhost"}}, "common_log": "127.0.0.1 - - [11/Nov/2021:14:33:44 +1000] \"GET / HTTP/2.0\" 0 0", "user_id": "", "duration": 0, "size": 0, "status": 0, "resp_headers": {"Server": ["Caddy"]}}
2021/11/11 04:33:44.030	DEBUG	http.stdlib	http2: panic serving 127.0.0.1:55386: runtime error: invalid memory address or nil pointer dereference
goroutine 28 [running]:
net/http.(*http2serverConn).runHandler.func1()
	net/http/h2_bundle.go:5816 +0x125
panic({0x1610d20, 0x2e29bc0})
	runtime/panic.go:1038 +0x215
github.com/greenpau/caddy-authorize/pkg/validator.(*TokenValidator).Authorize(0x444e6b4f37556b31, {0x228bf08, 0xc00003e100}, 0x7041774741517341)
	github.com/greenpau/caddy-authorize@v1.3.19/pkg/validator/sources.go:140 +0x36
github.com/greenpau/caddy-authorize/pkg/authz.Authorizer.Authenticate({{0xc0000439f8, 0x12}, {0xc000127d90, 0x7}, 0x0, {0x0, 0x0}, 0x0, 0x0, {0x0, ...}, ...}, ...)
	github.com/greenpau/caddy-authorize@v1.3.19/pkg/authz/authorizer.go:134 +0x10c
github.com/greenpau/caddy-authorize.AuthMiddleware.Authenticate({0xc000190300}, {0x7f10a6e0b758, 0xc001038810}, 0xc001042100)
	github.com/greenpau/caddy-authorize@v1.3.19/plugin.go:76 +0x1d8
github.com/caddyserver/caddy/v2/modules/caddyhttp/caddyauth.Authentication.ServeHTTP({0x0, 0xc000421200, 0xc00051a480}, {0x7f10a6e0b758, 0xc001038810}, 0xc001042100, {0x2268180, 0xc00003a1c0})
	github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyauth/caddyauth.go:76 +0x12a
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc000134920, {0x7f10a6e0b758, 0xc0010386c0}, 0xc001042100, {0x2268180, 0xc00003a1c0})
	github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/metrics.go:133 +0x51f
[...]
```

**Version Information**
```
$ ./caddy_linux_amd64_custom list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.6
http.authentication.hashes.scrypt v2.4.6
http.authentication.providers.http_basic v2.4.6
http.handlers.authentication v2.4.6
http.authentication.providers.authorize v1.3.19
http.handlers.authp v1.4.27
```

**Expected behavior**

I expected to see an error message about missing/incomplete config, however there is no error. Also, panic should not be occurring regardless of missing error.

**Comment by porjo** [comment]
Apologies, I created this under the wrong project!
