### ISSUE TITLE
breakfix: User transforms - can't match role before adding it

### ISSUE THREAD

**Issue by dczysz** [greenpau/caddy-auth-portal#203]
**Describe the issue**

I'm trying to add portal links for users with certain roles, but there's an error upon logging in if I don't first have a user transform to add the role to the user, even if the user already has the role in their user_db.json entry.

```
{"level":"debug","ts":1637271112.0612931,"logger":"http.stdlib","msg":"http2: panic serving 172.17.0.1:58456: interface conversion: interface {} is string, not []string\ngoroutine 62 [running]:\nnet/http.(*http2serverConn).runHandler.func1()\n\tnet/http/h2_bundle.go:5834 +0x125\npanic({0x162ada0, 0xc0006d0b10})\n\truntime/panic.go:1038 +0x215\ngithub.com/greenpau/caddy-authorize/pkg/acl.(*ruleStrCondExactMatchListStrInput).match(0x160b900, {0xc0006d0ae0, 0xc00009140a}, {0x1598840, 0xc0006e9620})\n\tgithub.com/greenpau/caddy-authorize@v1.3.20/pkg/acl/condition.go:370 +0xc9\ngithub.com/greenpau/caddy-authorize/pkg/acl.(*aclRuleAllow).eval(0xc001080540, {0x22970e8, 0xc000134000}, 0x40ceb4)\n\tgithub.com/greenpau/caddy-authorize@v1.3.20/pkg/acl/rule.go:4546 +0x6d\ngithub.com/greenpau/caddy-authorize/pkg/acl.(*AccessList).Allow(0xc000e598c0, {0x22970e8, 0xc000134000}, 0xc000060400)\n\tgithub.com/greenpau/caddy-authorize@v1.3.20/pkg/acl/acl.go:80 +0xb4\ngithub.com/greenpau/caddy-auth-portal/pkg/transformer.(*Factory).Transform(0x160b900, 0xc0006d0ae0)\n\tgithub.com/greenpau/caddy-auth-portal@v1.4.28/pkg/transformer/transformer.go:128 +0xef\ngithub.com/greenpau/caddy-auth-portal/pkg/authn.(*Authenticator).authorizeLoginRequest(0xc0002ada40, {0x2297158, 0xc0006d06c0}, {0x7f8367a91d50, 0xc0006d0960}, 0xc0011480c0, 0xc0003cadc0)\n\tgithub.com/greenpau/caddy-auth-portal@v1.4.28/pkg/authn/handle_http_login.go:130 +0x6a6\ngithub.com/greenpau/caddy-auth-portal/pkg/authn.(*Authenticator).handleHTTPLoginRequest(0xc000692b18, {0x2297158, 0xc0006d06c0}, {0x7f8367a91d50, 0xc0006d0960}, 0xc0000bcb00, 0xc0003cadc0)\n\tgithub.com/greenpau/caddy-auth-portal@v1.4.28/pkg/authn/handle_http_login.go:86 +0x1f6\ngithub.com/greenpau/caddy-auth-portal/pkg/authn.(*Authenticator).handleHTTPLogin(0xc0006067e1, {0x2297158, 0xc0006d06c0}, {0x7f8367a91d50, 0xc0006d0960}, 0xc0000bcb00, 0xc0003cadc0, 0x0)\n\tgithub.com/greenpau/caddy-auth-portal@v1.4.28/pkg/authn/handle_http_login.go:42 +0xdf\ngithub.com/greenpau/caddy-auth-portal/pkg/authn.(*Authenticator).handleHTTP(0xc0002ada40, {0x2297158, 0xc0006d06c0}, {0x7f8367a91d50, 0xc0006d0960}, 0xc0000bcb00, 0xc0003cadc0)\n\tgithub.com/greenpau/caddy-auth-portal@v1.4.28/pkg/authn/respond_http.go:63 +0xa47\ngithub.com/greenpau/caddy-auth-portal/pkg/authn.(*Authenticator).ServeHTTP(0xc0002ada40, {0x2297158, 0xc0006d06c0}, {0x7f8367a91d50, 0xc0006d0960}, 0xc0000bcb00, 0xc0003cadc0)\n\tgithub.com/greenpau/caddy-auth-portal@v1.4.28/pkg/authn/server.go:41 +0x1fb\ngithub.com/greenpau/caddy-auth-portal.AuthMiddleware.ServeHTTP({0xc000692df0}, {0x7f8367a91d50, 0xc0006d0960}, 0xc0000bcb00, {0x16c5400, 0xc0006d0960})\n\tgithub.com/greenpau/caddy-auth-portal@v1.4.28/plugin.go:75 +0xa7\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc000e5c760, {0x7f8367a91d50, 0xc0006d08a0}, 0xc0000bcb00, {0x2273100, 0xc000e5c9c0})\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/metrics.go:133 +0x51f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x7f8367a91d50, 0xc0006d08a0}, 0x2273100)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/routes.go:272 +0x3b\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2273100, {0x7f8367a91d50, 0xc0006d08a0}, 0x0)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x7f8367a91d50, 0xc0006d08a0}, 0xc0000bcb00)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/routes.go:244 +0x322\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000924000, {0x7f8367a91d50, 0xc0006d08a0}, 0x2273100)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc0002a3880, {0x7f8367a91d50, 0xc0006d08a0}, 0x6, {0x2273100, 0xc000e5c9c0})\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/subroute.go:74 +0x6d\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc000e5c780, {0x7f8367a91d50, 0xc0006d07e0}, 0xc0000bcb00, {0x2273100, 0xc000e5c9c0})\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/metrics.go:133 +0x51f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x7f8367a91d50, 0xc0006d07e0}, 0x2273100)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/routes.go:272 +0x3b\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2273100, {0x7f8367a91d50, 0xc0006d07e0}, 0x0)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x7f8367a91d50, 0xc0006d07e0}, 0xc0000bcb00)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/routes.go:244 +0x322\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000505b00, {0x7f8367a91d50, 0xc0006d07e0}, 0x2273100)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc0002a35a0, {0x7f8367a91d50, 0xc0006d07e0}, 0x6, {0x2273100, 0xc000e5c9c0})\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/subroute.go:74 +0x6d\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc000e5c7c0, {0x2289220, 0xc000822188}, 0xc0000bcb00, {0x2273100, 0xc000e5c9c0})\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/metrics.go:133 +0x51f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x2289220, 0xc000822188}, 0x2273100)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/routes.go:272 +0x3b\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2273100, {0x2289220, 0xc000822188}, 0x2)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2289220, 0xc000822188}, 0xc0000bcb00)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/routes.go:244 +0x322\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x748406, {0x2289220, 0xc000822188}, 0x181245d)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0xc0006d0720, {0x2289220, 0xc000822188}, 0x0, {0x2273100, 0xc000e5c9e0})\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/server.go:298 +0x252\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1({0x2289220, 0xc000822188}, 0x4988b7)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/server.go:274 +0x3b\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00015d4a0, {0x2289220, 0xc000822188}, 0xc0000bcb00)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc0005786c0, {0x2289220, 0xc000822188}, 0xc0000bcb00)\n\tgithub.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/server.go:210 +0x846\nnet/http.serverHandler.ServeHTTP({0x0}, {0x2289220, 0xc000822188}, 0xc0007d2900)\n\tnet/http/server.go:2878 +0x43b\nnet/http.initALPNRequest.ServeHTTP({{0x2297158, 0xc00072bfb0}, 0xc00021fc00, {0xc0004c69a0}}, {0x2289220, 0xc000822188}, 0xc0007d2900)\n\tnet/http/server.go:3479 +0x245\nnet/http.(*http2serverConn).runHandler(0x2285c28, 0x2ea5810, 0x0, 0x0)\n\tnet/http/h2_bundle.go:5841 +0x78\ncreated by net/http.(*http2serverConn).processHeaders\n\tnet/http/h2_bundle.go:5571 +0x510"}
```

**Configuration**

Paste full `Caddyfile` below:

```
{
	debug
}

https:// {
	tls internal {
		on_demand
	}
	route /auth* {
		authp {
			backend local /data/caddy/auth/user_db.json local
			crypto default token lifetime 21600
			crypto key sign-verify secret
			crypto key token name access_token
			ui {
				links {
					"Who am I" /auth/whoami
				}
			}
			transform user {
				match roles authp/admin
				ui link "Admin only" /admin
			}
		}
	}
	route /admin {
		authorize {
			primary yes
			crypto key token name access_token
			crypto key verify secret
			allow roles authp/admin
		}
		respond "Admin only!"
	}
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep auth` below:

```
http.authentication.hashes.bcrypt v2.4.6
http.authentication.hashes.scrypt v2.4.6
http.authentication.providers.http_basic v2.4.6
http.handlers.authentication v2.4.6
http.authentication.providers.authorize v1.3.20
http.handlers.authp v1.4.28
```

**Expected behavior**

I'm not sure why this error occurs when `webadmin` already has the `authp/admin` role by default.

If I add a transform to add the role before matching on it everything works as expected:
```
transform user {
	match email webadmin@localdomain.local
	action add role authp/admin
}
transform user {
	match roles authp/admin
	ui link "Admin only" /admin
}
```

This transform all by itself works as expected as well:
```
transform user {
	match email webadmin@localdomain.local
	ui link "Admin only" /admin
}
```

**Additional context**

Unfortunately, neither of those solutions are good options for what I'm trying to do.  This example is just using webadmin for simplicity, but the plan is to expose certain portal links to `manager` roles, but not regular `user` roles.  The `manager` and `user` emails are both on the same domain, so using the suffix match mentioned in the docs won't work for this either.

So I think my best option is to match by role, but it doesn't seem to work unless I redundantly add the role first.  Adding the role with a transform instead of just using the roles in user_db.json would require updating the Caddyfile any time a new manager account is created, instead of being able to rely on a simple `match roles` user transform.

**Comment by greenpau** [comment]
@dczysz , I will take a look at it. I never thought about matching by role to add a link 😄 Let me reproduce it.

**Comment by dczysz** [comment]
Haha no problem, thanks!

**Comment by greenpau** [comment]
@dczysz , confirmed the issue:

```
2021/11/19 01:11:27.510 DEBUG   http.stdlib     http2: panic serving 10.0.2.2:58191: interface conversion: interface {} is string, not []string
goroutine 83 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc00067aeb0, 0xc000243f8e, 0xc000b7e000)
        net/http/h2_bundle.go:5716 +0x193
panic(0x18ffdc0, 0xc0001b3a40)
        runtime/panic.go:965 +0x1b9
github.com/greenpau/caddy-authorize/pkg/acl.(*ruleStrCondExactMatchListStrInput).match(0xc000517f98, 0x25b5648, 0xc0000420b8, 0x18680e0, 0xc00013ec10, 0x1)
        github.com/greenpau/caddy-authorize@v1.3.20/pkg/acl/condition.go:370 +0xeb
github.com/greenpau/caddy-authorize/pkg/acl.(*aclRuleAllow).eval(0xc000abc7b0, 0x25b5648, 0xc0000420b8, 0xc0001b39e0, 0x3a)
        github.com/greenpau/caddy-authorize@v1.3.20/pkg/acl/rule.go:4546 +0x9a
github.com/greenpau/caddy-authorize/pkg/acl.(*AccessList).Allow(0xc000a528c0, 0x25b5648, 0xc0000420b8, 0xc0001b39e0, 0x1b19a01)
        github.com/greenpau/caddy-authorize@v1.3.20/pkg/acl/acl.go:80 +0x91
```


* **Use Case 1**: match role and add UI link

```
      transform user {
        match role authp/admin
        ui link "Portal Settings" /settings icon "las la-code-branch"
      }
```

* **Use Case 2**: match role and add another role

```
      transform user {
        match role authp/admin
        action add role authp/foo
      }
      transform user {
        match role authp/foo
        action add role authp/bar
      }
```

I am releasing a fix for this to work.

**Comment by greenpau** [comment]
@dczysz , please upgrade to [v1.4.30](https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.4.30) and you should be good to go.

**Comment by dczysz** [comment]
Awesome, thank you for the quick fix Paul!
